# Generated by Django 4.1.2 on 2022-11-24 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_address'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
    ]
