# Generated by Django 4.1.2 on 2022-11-25 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='User',
            new_name='user',
        ),
    ]
