# Generated by Django 4.1.2 on 2022-11-29 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_address_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='user',
        ),
    ]
